spring.application.name=ingestion-service
server.port=8080

# Configuración del Servidor Kafka
spring.kafka.bootstrap-servers=localhost:9092

# CONFIGURACIÓN DEL PRODUCTOR
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.springframework.kafka.support.serializer.JsonSerializer

spring.messages.basename=messages/errors